apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-1
  namespace: default
  labels:
    app: nginx
    test: pvc-timing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" # 使用默认存储类
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-2
  namespace: default
  labels:
    app: nginx
    test: pvc-timing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: "" # 使用默认存储类
